yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('posts.urls')),
    path('admin/', admin.site.urls),
]

yatube/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()


class Post(models.Model):
    text = models.TextField()
    pub_date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
    )
    group = models.ForeignKey(
        'Group',
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        related_name='posts',
    )

    class Meta:
        ordering = ('-pub_date',)


class Group(models.Model):
    title = models.CharField(
        max_length=200,
        db_index=True,
        verbose_name="Название группы",
    )
    slug = models.SlugField(
        max_length=255,
        unique=True,
        verbose_name="Адрес группы",
    )
    description = models.TextField(verbose_name="Описание группы")

    def __str__(self):
        return self.title

yatube/posts/views.py
from django.shortcuts import get_object_or_404, render
from .models import Group, Post

POST_COUNT: int = 10


def index(request):
    """Главная страница."""

    template = 'posts/index.html'
    title = 'Последние обновления на сайте'
    posts = Post.objects.all()[:POST_COUNT]

    context = {
        'title': title,
        'posts': posts,
    }

    return render(request, template, context)


def group_posts(request, slug):
    """Страница группы"""

    template = 'posts/group_list.html'
    group = get_object_or_404(Group, slug=slug)
    title = f'Записи сообщества {group.title}'
    posts = group.posts.all()[:POST_COUNT]

    context = {
        'title': title,
        'posts': posts,
    }

    return render(request, template, context)

yatube/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="ru">
  <head>
    <meta charset="utf-8">
    <!-- Сайт готов работать с мобильными устройствами -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Загружаем фав-иконки -->
    <link rel="icon" href="{% static 'img/fav/fav.ico' %}" type="image">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'img/fav/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'img/fav/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'img/fav/favicon-16x16.png' %}">
    <meta name="msapplication-TileColor" content="#000">
    <meta name="theme-color" content="#ffffff">
    <!-- Подключен файл со стандартными стилями бустрап -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <title>{{ title }}</title>
  </head>

  <body>

    <header>
      {% include 'includes/header.html' %}
    </header>

    <main>
      {% block content %}
        Контент не подвезли :(
      {% endblock %}
    </main>

    <footer class="page-footer font-small blue border-top">
      {% include 'includes/footer.html' %}
    </footer>

  </body>
</html>

yatube/templates/includes/footer.html
    <div class="footer-copyright text-center py-3">&copy 2020 Copyright
      <p><span style="color:red">Ya</span>tube</p>
    </div>

yatube/templates/includes/header.html
    {% load static %}
    <nav class="navbar navbar-light" style="background-color: lightskyblue">
      <div class="container">
         <a class="navbar-brand" href="{% url 'posts:index' %}">
         <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
         <span style="color:red">Ya</span>tube</a>
      </div>
    </nav>

yatube/templates/posts/group_list.html
{% extends 'base.html' %}

{% block content %}
  <div class="container py-5">
    <h1>{{ title }}</h1>
    <p>
      Группа тайных поклонников графа.
    </p>
    {% for post in posts %}
      <article>
        <ul>
          <li>
            Автор: {{ post.author.get_full_name }}
          </li>
          <li>
            Дата публикации: {{ post.pub_date|date:"d E Y" }}
          </li>
        </ul>
        <p>{{ post.text }}</p>
      </article>
      {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
  </div>
{% endblock %}

yatube/templates/posts/index.html
{% extends 'base.html' %}

{% block content %}
  <div class="container py-5">
    <h1>Последние обновления на сайте</h1>
      {% for post in posts %}
        <ul>
          <li>
            Автор: {{ post.author.get_full_name }}
          </li>
          <li>
            Дата публикации: {{ post.pub_date|date:"d E Y" }}
          </li>
        </ul>
        <p>{{ post.text }}</p>
        {% if post.group %}
          <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
        {% endif %}
        {% if not forloop.last %}<hr>{% endif %}
      {% endfor %}
  </div>
{% endblock %}